### ISSUE TITLE
Robot(real firmware) can not be built in  System Workbench for STM32.

### ISSUE THREAD

**Issue by MaKaRuiNah** [RiS3-Lab/p2im#1]
I notice that the project has the .cfg file(such as Robot Debug.cfg).Does the Robot miss the .cfg file?

**Comment by bofeng17** [comment]
I fixed this issue in https://github.com/RiS3-Lab/p2im-real_firmware/commit/32993e5a27bee2a56a7e51d498891bfcb05ed3ae

**Comment by MaKaRuiNah** [comment]
Thanks! it can be built now.Howerver,when i run the "../../../model_instantiation/fuzz.py -c fuzz.cfg", it throws the error:
"PROGRAM ABORT : Test case 'id:000000,orig:random' results in a crash"
<img width="478" alt="1" src="https://user-images.githubusercontent.com/24435177/89748442-db575d80-daf5-11ea-996e-4b6d45b05820.png">
<img width="550" alt="2" src="https://user-images.githubusercontent.com/24435177/89748447-e14d3e80-daf5-11ea-9733-3e2e80b3d4f0.png">
I have found that i set the wrong mcu in the fuzz.cfg.Does the mcu have the only following choices?
board       = STM32F429I-Discovery  
mcu         = STM32F429ZI   
board       = NUCLEO-F103RB    
mcu         = STM32F103RB   
board       = Arduino-Due
mcu         = SAM3X8E   
board       = FRDM-K64F
mcu         = MK64FN1M0VLL12

**Comment by bofeng17** [comment]
The emulator only supports 4 MCUs. You can either recompile your firmware to use one of the MCUs supported, or add your own MCU to the emulator following the instructions in https://github.com/RiS3-Lab/p2im/blob/master/docs/add_mcu.md

**Comment by MaKaRuiNah** [comment]
Thanks!When i want to test a new firmware, and i use the same board and mcu as yours,it throws an error,how can i solve it?
<img width="533" alt="1" src="https://user-images.githubusercontent.com/24435177/90001066-8c5f2300-dcc3-11ea-8078-5ed55ce7d56c.png">

**Comment by bofeng17** [comment]
The firmware hangs when running with the seed input. You may want to dump the execution trace to see where the firmware hangs. 

Please append `-d exec,int -D qemu.log` option to the command below and run it. 
![image](https://user-images.githubusercontent.com/14085560/90069204-f970b980-dcbf-11ea-9c6e-6741a346e956.png)
The firmware execution trace is dumped to `qemu.log`.

**Comment by MaKaRuiNah** [comment]
Thank you very much! I want to know where the code crashes, i run the "run_fw.py".however, i only get the address(like 0x08003658),can i get the line number where the code crashes?
<img width="944" alt="1" src="https://user-images.githubusercontent.com/24435177/90222372-8477be00-de3e-11ea-8f1a-68a4bf42999d.png">
