### ISSUE TITLE
How to get the qemu log information, when afl is running.

### ISSUE THREAD

**Issue by liuliqaz** [RiS3-Lab/p2im#10]
Hello, I try to get the qemu log information, when afl is running. when I change the "cmd_afl_qemu" in fuzz.py, add "-d out_asm" at 
the end of cmd_afl_qemu, the afl can not run and stop in perform_dry_run().
And I found there is a configuration option in fuzz.cfg, so I change the [qemu] log and add -D qemu.log, the program run and can not stop by creating new file like 0_ranom.xxx.
I try to catch the assembly code runned in every loop in AFL. 
Thank you for hlep!!!!

**Comment by bofeng17** [comment]
Dumping qemu log slows down the execution a lot, so I don't recommend you to do that during fuzzing. However, you can dump qemu log offline after the fuzzing process. You can run a fuzzer-generated test case by [`run_fw.py`](https://github.com/RiS3-Lab/p2im/#analyzing-crashinghanging-input) and dump qemu logs by appending `-d` and `-D` option to `cmd` in `run_fw.py`.
