### ISSUE TITLE
KeyError:255, QEMU's return value is not found

### ISSUE THREAD

**Issue by youngwoo013** [RiS3-Lab/p2im#13]
Hello, I am studying and experimenting on P2IM.
I want to run firmware using P2IM.The error "KeyError:255" occurs in the me.py code. This means that the return value will be 0xff when QEMU is run as subprocess and it is not defined as the rv dictionary of me.py code. This results in an error.
**What is the meaning of the return value of the QEMU, 0xff?**

![KeyError255](https://user-images.githubusercontent.com/23147086/115107569-a5347c80-9fa6-11eb-9504-fc35856d8b7b.png)

If I ignore this error and proceed, **there is a myriad of rounds with the phrase "There is aup, run Me."** (where the "Stage 2 returned to unexpected reasons!" part indicates a KeyError:255 error, and simply added 0xff to the dictionary not to print errors.)

![image](https://user-images.githubusercontent.com/23147086/115107698-808cd480-9fa7-11eb-956b-337156d8c0a6.png)

And at the end, fuzzing does not proceed with the following error.
**I proceeded with the firmware that added the mcu and startForkserver part, and I wonder how to solve the error.**

![image](https://user-images.githubusercontent.com/23147086/115107725-a7e3a180-9fa7-11eb-8874-2a1f9ddd04d5.png)

**Comment by bofeng17** [comment]
Thanks for your interest in P2IM.

Return value 0xff means qemu detects an illegal memory read/write which is outside ram, flash, or peripheral regions. The check is performed at https://github.com/RiS3-Lab/p2im/blob/master/qemu/src/qemu.git/softmmu_template.h#L186-L197 and  https://github.com/RiS3-Lab/p2im/blob/master/qemu/src/qemu.git/softmmu_template.h#L414-L423. The flash and ram region is per MCU specified in `hw/arm/stm32-mcus.c`.

To figure out which instruction in firmware triggered the illegal access, please run the qemu command printed right above your first screenshot in your shell.

**Comment by youngwoo013** [comment]
I'm sorry for the late reply. I couldn't solve the problem, but it helped me a lot to figure it out. Thank you.
