### ISSUE TITLE
Encounter a problem: get qemu log when fuzzing and then can not find crash anymore

### ISSUE THREAD

**Issue by liuliqaz** [RiS3-Lab/p2im#14]
Hello, I change function "get_qemu_arg()" like follow, try to get firmware running log when fuzzing. After change, I can not get any crash in fuzzing. If I change back, I can find a crash.

![q](https://user-images.githubusercontent.com/56335649/116682735-382ad900-a9e1-11eb-9781-e3ac2f1bfa02.png)

Thanks for your help!!!

**Comment by dokodokoR** [comment]
@liuliqaz 
The execution time may have been increased by the log, and it may have been determined to be a "outputs/hang".

**Comment by bofeng17** [comment]
I agree with @dokodokoR that dumping log during fuzzing is very slow and are likely to cause hangs during fuzzing. You can rerun the fuzzer-generated test cases offline to dump log.
