### ISSUE TITLE
Generated model can fail validation when loaded

### ISSUE THREAD

**Issue by guyf2010** [RiS3-Lab/p2im#17]
It appears that models generated during fuzzing can exceed the limits enforced in peri-mod.c

23 hours into fuzzing the supplied gateway firmware, the number of paths found stopped growing. Rerunning any of the found crashes using the last peripheral model gives the error "error: too many events! Fail to load model from file" before execution of the firmware starts. The second to last peripheral model does trigger the crashes as expected.

Please let me know if you need a copy of any of the generated files.

**Comment by bofeng17** [comment]
yes, it's a known issue. Change https://github.com/RiS3-Lab/p2im/blob/master/qemu/src/qemu.git/include/peri-mod/peri-mod.h#L111 and recompile QEMU will solve this issue
