### ISSUE TITLE
Where to locate peri-mod/peri-mod.h

### ISSUE THREAD

**Issue by newthis** [RiS3-Lab/p2im#3]
in qemu.git/hw/arm/peri-mod.c peri-mod.c file，
it include ""peri-mod/peri-mod.h"， but I can not
find this file，so what is the location of file peri-mod/peri-mod.h?

**Comment by bofeng17** [comment]
You can found it here https://github.com/RiS3-Lab/p2im/blob/master/qemu/src/qemu.git/include/peri-mod/peri-mod.h
