### ISSUE TITLE
Crash Analysis

### ISSUE THREAD

**Issue by findo** [RiS3-Lab/p2im#5]
I use p2im to find some crashes. After running some crash file with run_fw.py script without '--debug', QEMU always prints 'Run of of input bytes' or 'illegal read at xxx'. Are these crash files really the input cause firmware to crash ?

**Comment by bofeng17** [comment]
Based on my experience, 'illegal read at xxx' is likely caused by bugs. A fuzzer run terminates when 'Run of of input bytes', so it's not caused by bugs.
